name: currency_exchanger
description: "Project to exchange BRL to a user inputted currency."


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:

  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  get_it: ^7.6.4
  logger: ^2.5.0
  result_dart: 1.1.1
  very_good_analysis: ^6.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.4


flutter:
  uses-material-design: true
